kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "${WAVE-PVC-NAME}"
  namespace: "${SPARK_APPLICATIONS_NAMESPACE}"
  annotations:
    volume.beta.kubernetes.io/storage-class: "${WAVE_EFS_PROVISIONER_STORAGE_CLASS_NAME}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi